version: "3.8"
services:
  postgresql:
    image: postgres:latest
    container_name: docker_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - local-pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: docker_dbbench
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    ports:
      - "8888:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local-pgdata:
  pgadmin-data:      